# Generated by Django 2.2.4 on 2019-08-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appdawak', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name_plural': 'Medicine'},
        ),
    ]
